### ISSUE TITLE
Getting errors making this up and running

### ISSUE THREAD

**Issue by ranvijayj** [israel-fl/python3-logstash#2] opened 2018-07-11 18:32 UTC
return str.encode(self.formatter.format(record)) + b'\n'
TypeError: descriptor 'encode' requires a 'str' object but received a 'bytes'
Call stack:
  File "manage.py", line 22, in <module>

Could you help?

**Comment by tiagofernandez** [comment] 2018-07-12 07:54
I think the [PR](https://github.com/israel-fl/python3-logstash/pull/1) I sent could fix this, but @israel-fl hasn't uploaded a new version to Pypi yet. Meanwhile, you can clone this repo and give it a try.

**Comment by israel-fl** [comment] 2018-07-12 15:51
Hey @ranvijayj, @tiagofernandez, sorry I'd been meaning to get to this.

The latest version of the project, with the [PR](https://github.com/israel-fl/python3-logstash/pull/1) has been submitted to PyPi.

I am however having trouble getting PIP to see it without the `--no-cache-dir` command.

To be more clear, if you can't see version [0.4.80](https://pypi.org/project/python3-logstash/0.4.80/), run the following command:

```
pip3 install python3-logstash==0.4.80 --no-cache-dir
```

@tiagofernandez is right, his PR should have fixed the issue you are having. I'm closing this issue for now.

**Closed as completed** 2018-07-12 15:52 UTC

**Comment by AlexisVLRT** [comment] 2019-09-29 14:46
Hi @israel-fl, @tiagofernandez 

It seems the discussed PR breaks the intended behaviour for the UDP `LogstashHandler` which now throws `TypeError: descriptor 'encode' requires a 'str' object but received a 'bytes'` with the 0.4.80 version.

I tested this with python 3.6 on Windows 8.1 and python 3.7 on Debian 9
